version: '3'
services:
  neo4j:
    image: neo4j:community-ubi9
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/1q2w3e4r!!
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - ./data:/data
      - ./plugins:/plugins
      - ./import:/import